version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./rails-on-docker-compose:/var/app
      - ./rails-on-docker-compose/gem_cache:/usr/local/bundle/gems
      - ./rails-on-docker-compose/node_modules:/var/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
